# basic options
title: Processing sample code 
author: Mari Menegon
email: your-email@domain.com
description: Structured molecules 
twitter_username: jekyllrb
github_username:  marimenegon

# Build settings
markdown: kramdown
theme: minima
